name: UDMP Podman

on:
  workflow_dispatch:
  push:
    paths:
      - 'podman-update/build/Dockerfile'
  pull_request:
    paths:
      - 'podman-update/build/Dockerfile'
jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --file podman-update/build/Dockerfile --tag boostchicken:udmp-podman podman-update/build/
    - name: Docker Extract
      id: extract
      uses: shrink/actions-docker-extract@v1
      with:
        # Docker Image to extract files from
        image: boostchicken:udmp-podman
        # Path (from root) to a file or directory within Image
        path: tmp/release/podman-install.zip
    - name: Upload Podman Install
      uses: actions/upload-artifact@v2
      with:
        path: ${{ steps.extract.outputs.destination }}
        name: podman-install.zip
 
