name: UDM-SE/PRO Podman

on:
  workflow_dispatch:
  push:
    paths:
      - 'podman-update/build/Dockerfile'
      - 'podman-update/build/podman.Makefile.UDM-Pro-SE.patch'
  pull_request:
    paths:
      - 'podman-update/build/Dockerfile'
      - 'podman-update/build/podman.Makefile.UDM-Pro-SE.patch'

jobs:

  build:

    runs-on: self-hosted

    steps:


    - uses: actions/checkout@v3
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v2.1.0
      with:
        platforms: arm64
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.5.0
    - name: Build the Docker image
      run: DOCKER_BUILDKIT=1 docker build --file podman-update/build/Dockerfile --build-arg UDM_PLATFORM=UDM-Pro-SE --tag boostchicken:udm-podman podman-update/build/
    - name: Docker Extract
      id: extract
      uses: boostchicken-dev/actions-docker-extract@v3
      with:
        # Docker Image to extract files from
        image: boostchicken:udm-podman
        # Path (from root) to a file or directory within Image
        path: /tmp/install/.
        
    - name: Generate new tag version
      id: version
      uses: flynshue/version-action@v0.0.1
      
    - name: Upload Podman Install
      uses: actions/upload-artifact@v3.1.2
      with:
        path: ${{ steps.extract.outputs.destination }}
        name: podman-udmse-udmpro-${{ steps.version.outputs.version }}
        retention-days: 90
